import Head from "next/head";
import Footer from "../components/Footer";
import Search from "../components/Search";

export default function Home() {
  return (
    <div className="bg-white text-black">
      <Head>
        <title>Cek RS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto my-auto flex h-screen max-w-screen-md flex-col items-center justify-center">
        <h1 className="text-center text-5xl font-bold">
          Cek Ketersediaan Tempat Tidur Rumah Sakit
        </h1>
        <div className="mt-4 mb-1 w-full border-t border-black/20"></div>
        <div className="flex w-full">
          <Search />
        </div>
        <Footer />
      </div>
    </div>
  );
}
