import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-white text-black">
      <Head>
        <title>Cek RS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto flex h-screen max-w-screen-md items-center justify-center">
        <div className="flex flex-col">
          <h1 className="text-center text-5xl font-bold">
            Cek Ketersediaan Tempat Tidur Rumah Sakit
          </h1>
          <div className="mt-4 w-full border-t border-black/20"></div>
        </div>
        <div className="">
          <Search />
        </div>
      </div>
    </div>
  );
}
